spring.application.name=event-ticketing

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:ticketingdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL to prove concurrency atomic updates in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize Database using data.sql
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

# Server port
server.port=8080
